version: "3.9"
services:
    vue-app:
        build: ./frontend
        command: npm run serve
        hostname: vue-app
        ports:
          - "8080:8080"
        volumes:
          - ./frontend/src:/frontend/usr/app/src
          - ./frontend/nodemon.json:/frontend/usr/app/nodemon.json
        environment: 
          - CHOKIDAR_USEPOLLING=true

    node-app:
        build: ./backend
        command: npm run dev
        hostname: node-app
        ports:
          - "3000:3000"
        volumes:
          - ./backend/src:/backend/usr/app/src
          - ./backend/nodemon.json:/backend/usr/app/nodemon.json
