version: "3.9"
services:
    csv-parser:
        build: .
        command: npm run dev
        hostname: csv-parser
        ports:
            - "3000:3000"
        volumes:
          - ./src:/usr/app/src
          - ./nodemon.json:/usr/app/nodemon.json
